steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/vbcarlos23/asulado-mlops.git
        cd asulado-mlops

  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd asulado-mlops
        pip install -r requirements.txt

  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd asulado-mlops
        python build_pipeline.py

  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd asulado-mlops
        python run_pipeline.py

# Opcional: Despliegue autom치tico del modelo si es necesario
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd asulado-mlops
        python deploy_model.py

# Artifacts
artifacts:
  objects:
    location: 'gs://interno-davinci-analitica-bucket/resultados/'
    paths: ['**']

# Configuraci칩n adicional
timeout: 3600s  # Tiempo de espera m치ximo para la construcci칩n
