steps:
  - name: 'gcr.io/interno-davinci-analitica/asulado-mlops:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /app
        python build_pipeline.py

  - name: 'gcr.io/interno-davinci-analitica/asulado-mlops:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /app
        python run_pipeline.py

# Opcional: Despliegue autom치tico del modelo si es necesario
  - name: 'gcr.io/interno-davinci-analitica/asulado-mlops:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /app
        python deploy_model.py

# Artifacts
artifacts:
  objects:
    location: 'gs://interno-davinci-analitica-bucket/resultados/'
    paths: ['**']

# Configuraci칩n adicional
timeout: 3600s  # Tiempo de espera m치ximo para la construcci칩n
